server:
  port: ${SPRING.APPLICATION.PORT:8080}
  servlet:
    context-path: /v1

spring:
  profiles:
    default: cloud
  application:
    name: aibroker-service
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  security:
    jwt:
      secret-key: ${SPRING.SECURITY.JWT.SECRET_KEY}
      expiration: ${SPRING.SECURITY.JWT.EXPIRATION}
