server:
  port: 8083
  servlet:
    context-path: /v1

spring:
  application:
    name: aibroker-service
  datasource:
    url: ${SPRING.DATASOURCE.URL}
    username: ${SPRING.DATASOURCE.USERNAME}
    password: ${SPRING.DATASOURCE.PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  security:
    jwt:
      secret-key: ${SPRING.SECURITY.JWT.SECRET_KEY}
      expiration: ${SPRING.SECURITY.JWT.EXPIRATION}
